=== What is the potential impact?

Fortunately, in the case of MWS tokens, Amazon provides the ability to set
short token lifetimes.

However, once the malicious user has the MWS key, they may be able to
authenticate and access AWS resources on behalf of the compromised account or
user.

From this point, the impact of this security issue depends on how well the
organization was protected and how strongly the principle of least privilege
was applied to the affected IAM account.

==== Data Theft Manipulation

The malicious users now have the ability to steal various types of data stored
in the seller account on Amazon's platform, including customer information,
sales data, order details, shipping addresses, financial records, and product
listings.

Furthermore, this vulnerability enables them to perform actions on behalf of
the seller:

* Manipulate product listings
* Change pricings
* Update Inventory levels

==== Financial and reputational toll

Unauthorized access to an Amazon seller account can enable malicious actors to
engage in fraudulent activities, such as:

* manipulating sales figures
* redirecting funds
* initiating unauthorized refunds
* posting fake reviews
* manipulating rankings
* engaging in prohibited activities

