
include:description.adoc[]

==== Data Theft

The malicious users now have the ability to steal various types of data stored
in the Cloud services, such as customer information, intellectual property,
financial data, or other sensitive data.

This vulnerability affects a number of services, including:

* Data storage buckets
* Relational databases
* Code repositories or version control systems, which can expose proprietary code and sensitive algorithms
* Secret managers, when the user has access to other secrets that are supposed to be hidden
* Backups

==== Termination of service

With compromised credentials, an attacker can terminate various types of
services, resulting in the loss of virtual servers, clusters and all data
stored on them.

For example:

* virtual machines, services and load balancers
* Database instances
* Kubernetes clusters and containers
* Serverless functions

==== Malicious exploitation on a large scale

With the goal of either undermining the organization's reputation or profiting
from newly acquired computing capabilities, malicious users can also perform a
variety of actions that are not always publicized in the mainstream media.

Such examples include

* Mining cryptocurrencies by exploiting the computing resources of compromised instances or containers for their own profit.
* Malware distribution and remote control by building a network of compromised instances or containers to form a botnet that can be used for DDoS attacks, spam distribution, malware distribution, or other malicious activities
* Phishing or spoofing architectures. From the victim's perspective, the attack originates from the victim's organization rather than a malicious organization


== How to fix it

=== Revoke the secret

=== Use a secret manager in backends
Do not move it elsewhere in the code

=== Use keystores in frontends

=== API access review for malicious activity
Recent accesses to the Cloud API should be reviewed to make sure no malicious use was performed.
