=== What are the possible effects?

Fortunately, in the case of session secrets, AWS provides the ability to
integrate session tokens with multi-factor authentication (MFA), along with
short token lifetimes.

However, if an attacker gets hold of a leaked secret session key, they can
penetrate the target organization in two ways:

* First, by attacking the organization as quickly as possible and generating more keys for themselves
* Second, by figuring out how the secret was built into the code.
** For example, if a service account has hard-coded the key, there is a good chance that a new session key has been leaked again. In this case, waiting or triggering the new leak is a way to break into the system.

Once in possession of the secret session key, the malicious user may be able to
authenticate and access AWS resources on behalf of the compromised account or
user.

From this point, the impact of this security issue depends on how well the AWS
organization was protected and how strongly the principle of least privilege
was applied to the affected IAM account.

include::impact.adoc[]
