=== What are the possible effects?

Fortunately, in the case of secret access keys and key IDs, AWS has taken care
to ensure that the system only grants access if two different strings are
specified.

If an attacker gets hold of a leaked secret access key, they can try to guess
or deduce the associated access key ID or use other methods to find it. In the
worst case, the access key ID is stored right next to the secret key.

Once the malicious user has both the ID access key and the secret access key,
he may be able to authenticate and access AWS resources on behalf of the
compromised account or user.

From this point, the impact of this security issue depends on how well the AWS
organization was protected and how strongly the principle of least privilege
was applied to the affected IAM account.

==== Data Theft

The malicious users now have the ability to steal various types of data stored
in AWS services, such as customer information, intellectual property, financial
data, or other sensitive data dATA.

This vulnerability affects a number of AWS services, including:

* S3 buckets
* RDS databases
* Code repositories or version control systems, which can expose proprietary code and sensitive algorithms
* Secrets Manager, when the user has access to other secrets that are supposed to be hidden
* Backups

==== Termination of service

With compromised credentials, an attacker can terminate various types of
services, resulting in the loss of virtual servers, clusters and all data
stored on them.

For example:

* EC2 instances and load balancers
* RDS instances
* EKS and ECS clusters
* S3 buckets and lambda functions

==== Malicious exploitation on a large scale

With the goal of either undermining the organization's reputation or profiting
from newly acquired computing capabilities, malicious users can also perform a
variety of actions that are not always publicized in the mainstream media.

Such examples include

* Mining cryptocurrencies by exploiting the computing resources of compromised instances or containers for their own profit.
* Malware distribution and remote control by building a network of compromised instances or containers to form a botnet that can be used for DDoS attacks, spam distribution, malware distribution, or other malicious activities
* Phishing or spoofing architectures. From the victim's perspective, the attack originates from the victim's organization rather than a malicious organization
